import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const storage=new Map();
const context=vm.createContext({window:{HLU_CONFIG:{},HLUPresentation:{translate:x=>x}},document:{querySelector:()=>({}),createElement:()=>({set innerHTML(x){this.textContent=x.replace(/<[^>]+>/g,'');}})},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)},URL,location:{href:'https://example.test/hlu/'}});
vm.runInContext(fs.readFileSync('assets/icons.js','utf8'),context);
const source=fs.readFileSync('assets/app.js','utf8').replace('\nstart();\n','\nwindow.__test={normalize,extract,sortRows,resourceTabFor,latestResourceArticles,card,setResources:rows=>{resources=rows;}};\n');
vm.runInContext(source,context);
const app=context.window.__test;
const rows=[{id:'s',section:'soft',title:'Ứng dụng',visible:true},{id:'f',section:'firmware',title:'Firmware',visible:true},{id:'n',section:'news',title:'Tin mới',visible:true}];
assert.equal(app.extract(rows).map(x=>x.section).join(','),'soft,firmware,news');
assert.equal(app.extract({data:rows}).map(x=>x.section).join(','),'soft,firmware,news');
assert.equal(app.normalize(rows[0],0,rows).section,'soft','Array.map third argument cannot force docs');
assert.equal(app.sortRows(app.extract([{id:'unknown',section:'unexpected',title:'Unknown'}])).length,0,'Unrecognized sections must not become documents');
assert.equal(app.resourceTabFor({section:'soft',title:'Hướng dẫn'}),'other');
assert.equal(app.resourceTabFor({section:'firmware',title:'Biểu mẫu'}),'other');
assert.equal(app.resourceTabFor({section:'docs',title:'Hướng dẫn cài đặt'}),'guides');
assert.equal(app.resourceTabFor({section:'docs',title:'Biểu mẫu báo cáo'}),'templates');
app.setResources(app.extract(Array.from({length:8},(_,i)=>({id:String(i),section:i===7?'news':'soft',title:String(i),createdAt:i===6?'invalid':`2026-10-0${i+1}`,updatedAt:i===6?'2026-10-09':'2026-10-01',sortOrder:i}))));
// Android falls back to updatedAt when createdAt is invalid, not only when it is empty.
assert.equal(app.latestResourceArticles().length,5);
assert.equal(app.latestResourceArticles()[0].id,'6');
assert(!app.latestResourceArticles().some(x=>x.section==='news'));
const noDownload=app.normalize({id:'view',title:'View only',section:'docs',viewUrl:'https://example.test/view'},0);
assert(!app.card(noDownload,{download:true}).includes('data-download-item'));
const download=app.normalize({id:'file',title:'File',section:'soft',downloadUrl:'https://example.test/file'},0);
assert(app.card(download,{download:true}).includes('data-download-item'));
assert(app.card(download,{download:true}).indexOf('data-fav')<app.card(download,{download:true}).indexOf('data-download-item'));
assert(app.card(download,{saved:true}).includes('data-icon="starBorder"'));
console.log('Runtime regressions passed: API/cache section mapping, resource facets, latest selection, conditional downloads, action order, saved icon.');
